name: Update Test cases README

on:
  push:
    paths:
      - 'data/test_cases.json'
      - 'data/update_readme.py'
      - '.github/workflows/update_test_cases.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update README
      run: python data/update_readme.py --input data/test_cases.json --output test_cases.md
    - name: Commit changes
      run: |
        git config --local user.email "sunny_yyh_0116@163.com"
        git config --local user.name "live-high"
        git add test_cases.md
        git commit -m "DOC: Update Test cases README" || echo "No changes to commit"
        git push
