name: Update Test cases README

on:
  push:
    paths:
      - 'data/test_cases.json'
      - 'data/update_readme.py'
      - '.github/workflows/update_test_cases.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update README
      run: python data/update_readme.py --input data/test_cases.json --output test_cases.md
    
    - uses: Readme-Workflows/readme-replacer@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Those are all default values and only are shown for demonstration
        TEMPLATE_FILE: 'data/test_cases.json'
        COMMIT_FILE: 'test_cases.md'
          

